# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sat, 13 Mar 2010 09:09:21 +0100
*	@wiki%2dnutzer	1
*	@wiki%2dchefredakteure	16
*	@wiki%2dredakteure	8
*	@ALL	0
#wiki:dokuwiki	@ALL	1
#wiki:navigation	@ALL	1
#start	@ALL	1
#wiki:*	@ALL	1
