<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings 
 * Auto-generated by config plugin 
 * Run for user: admin
 * Date: Sat, 13 Mar 2010 09:10:34 +0100
 */

$conf['title'] = 'organization';
$conf['lang'] = 'de';
$conf['template'] = 'monobook';
$conf['useacl'] = 1;
#$conf['superuser'] = '@admin';
$conf['superuser'] = 'domadmin';
// end auto-generated content

// keine offene Benutzerregistrierung
$conf['openregister'] = 0;

// LDAP Connect
$conf['authtype'] = 'authldap';
$conf['auth']['ldap']['server'] = 'localhost';
$conf['auth']['ldap']['port'] = '389';
$conf['auth']['ldap']['starttls'] = 0;
$conf['auth']['ldap']['version'] = '3';
$conf['auth']['ldap']['binddn'] = 'uid=admin,ou=Benutzerverwaltung,basedn';
$conf['auth']['ldap']['bindpw'] = 'admin-secret';
$conf['auth']['ldap']['usertree'] = 'ou=users,ou=Benutzerverwaltung,basedn';
$conf['auth']['ldap']['grouptree'] = 'ou=groups,ou=Benutzerverwaltung,basedn';
$conf['auth']['ldap']['userfilter'] = '(&(uid=%{user})(objectClass=posixAccount))';
$conf['auth']['ldap']['groupfilter'] = '(&(objectClass=posixGroup)(|(gidNumber=%{gid})(memberUID=%{user})))';

?>