#!/bin/bash
# Script zur zyklischen Virenprüfung der Fileserver-Freigaben
# (C) 2009 invis-server.org
# Author: Stefan Schäfer <stefan@invis-server.org>
# Questions: http://forum.invis-server.org
# License: GPLv3

#Konfigurationsdaten
conffile="/etc/invis/invis.conf"

# Funktionen
# Werte aus Konfigurationsdatendatei extrahieren
# $1 = Konfigurationsdatei, $2 = Parameter, $3 Wert (Feld)
getconfdata() {
    cat $1 |grep "$2" | cut -d ":" -f $3
}

# Konfigurationsparameter tauschen
changevalues() {
    # Arg1 = Pfad, Arg2 = Datei, Arg3 = sed String
    cat $1/$2|sed "s%$3%g" > $1/$2.new
    mv $1/$2.new $1/$2
}

# Basis-Variablen
doavrun=`getconfdata $conffile "avCheck" "2"`
scanner=`getconfdata $conffile "AV" "2"`
quardir=`getconfdata $conffile "quarDir" "2"`

if [[ $doavrun == "j" ]]; then
    if [[ $scanner == "antivir" ]]; then
	avscan --allfiles --scan-in-archive -q -r1 -lang=DE -s --moveto=$quardir /var/lib/samba/profiles/
	avscan --allfiles --scan-in-archive -q -r1 -lang=DE -s --moveto=$quardir /srv/shares
	avscan --allfiles --scan-in-archive -q -r1 -lang=DE -s --moveto=$quardir /home
    else
	clamscan -r -i --log=/var/log/clamscan --move=$quardir /var/lib/samba/profiles/
	clamscan -r -i --log=/var/log/clamscan --move=$quardir /srv/shares
	clamscan -r -i --log=/var/log/clamscan --move=$quardir /home
    fi
fi
